version: "3.8"

services:
  service-a:
    image: YOUR_DOCKERHUB_USER/service-a:latest
    environment:
      - PORT=8000
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/ || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    # Optional shared volume mount for local dev
    # volumes:
    #   - shared-data:/shared

  service-b:
    image: YOUR_DOCKERHUB_USER/service-b:latest
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      service-a:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:3000/ || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    # volumes:
    #   - shared-data:/shared

# volumes:
#   shared-data:

